
Table users {
  id integer [pk, increment]
  email text [unique, not null]
  password text [not null]
  company_name text [not null]
  created_at datetime [default: `CURRENT_TIMESTAMP`]
}

Table candidates {
  id integer [pk, increment]
  name text [not null]
  email text [not null]
  created_at datetime [default: `CURRENT_TIMESTAMP`]
}

Table tests {
  id integer [pk, increment]
  user_id integer [ref: > users.id, not null]
  name text [not null]
  instructions text [not null]
  time_limit integer [not null]
  tests_code text [not null]
  created_at datetime [default: `CURRENT_TIMESTAMP`]
}

Table assessments {
  id integer [pk, increment]
  test_id integer [ref: > tests.id, not null]
  candidate_id integer [ref: > candidates.id, not null]
  status text [default: 'NOT TAKEN']
  start_time datetime
  end_time datetime
  score integer
  token text [unique, not null]
}

